### PR TITLE
Editing pass

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR contains an editing pass through the main text.

### CODE REVIEW

**Comment by alimanfoo** [comment]
One previous comment from DK is that abstract was too long, and I think he's right. I've tried to shorten it a bit.

**Comment by alimanfoo** [comment]
Added some edits to results describing the nonsynonymous variants, mostly to update with new information from the phase 2 populations, and to streamline a little.

**Comment by alimanfoo** [comment]
Hi @cclarkson, this is good to go AFAIC.

**Review by cclarkson — APPROVED** [review]
LGTM :+1:

**Pull request merged**
