### PR TITLE
Vgsc median joining networks - ready for review

### PR DESCRIPTION
**Pull request by cclarkson**

### CODE REVIEW

**Comment by cclarkson** [comment]
The clusters have been generated, this PR is just awaiting the hierarchical clusters to be named so we can examine concordance with median joining.

**Comment by cclarkson** [comment]
Hi @alimanfoo,

This is ready for review - we will need to come back to which 'non-KDR' clusters/networks to investigate and take downstream to other analyses.

**Comment by cclarkson** [comment]
Hi @alimanfoo - this is ready for review.

I pruned the variant labels in the same fashion as phase 1, removing singleton edge labels.

**Review by alimanfoo — APPROVED** [review]
Hi Chris, this is looking great to me, no objections if you want to merge.

**Pull request merged**
